datasets:
- name: local
  type: local
  config:
    path: "C:/Users/ASUS/Desktop/LuminaLM/Data"
    pattern: "*.txt"

- name: openwebtext
  type: huggingface
  config:
    dataset_name: "stas/openwebtext-10k"
    split: "train[:1000]"
    cache_dir: ".cache/openwebtext"

- name: medical_qa
  type: huggingface
  config:
    dataset_name: "medalpaca/medical_qa_512"
    split: "train"
    cache_dir: ".cache/medical"