datasets:
- name: local
  type: local
  config:
    path: "C:/Users/ASUS/Desktop/LuminaLM/Data"
    pattern: "*.txt"

- name: openwebtext
  type: huggingface
  config:
    dataset_name: "william_fedus/shakespeare"
    split: "train"
    cache_dir: ".cache/openwebtext"

- name: medical_qa
  type: huggingface
  config:
    dataset_name: "medical_dialog"
    split: "train"
    cache_dir: ".cache/medical"