datasets:
- config:
    path: "C:/Users/ASUS/Desktop/LuminaLM/Data"
    pattern: '*.txt'
  name: local
  type: local
- name: openwebtext
  type: huggingface
  config:
    dataset_name: "stas/openwebtext-10k"
    streaming: false
    split: "train"
    trust_remote_code: true
    use_auth_token: true
    revision: "main"
- name: medical_qa_all
  type: huggingface
  config:
    dataset_name: "Malikeh1375/medical-question-answering-datasets"
    config: "all-processed"  # Corrected key
    streaming: false
    split: "train"
    trust_remote_code: true